## variables --Data memory

In [1]:
def test():
    return
test()
    

In [2]:
class Demo:
    def Test(self):
        print("test() for the class and method")
        return

obj = Demo()
obj.Test()

test() for the class and method


In [3]:
class Demo1:
    def fact(self,n):
        #return the factorial
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
p1=Demo1()
print(p1.fact(5))#120

120


In [4]:
class Demo2:
    def Accept(self,p1,p2):
        a=p1
        b=p2
        return
    def display(self):
        print("a= ",a)
        print("b= ",b)
        
c1 = Demo2()
c1.accept(10,20)
c1.display()

AttributeError: 'Demo2' object has no attribute 'accept'

In [8]:
class Demo2:
    def __init__(self,p1,p2):
        self.p1 = p1
        self.p2 = p2
        
    def add(self,p1,p2):
        return p1 + p2
    
c1 = Demo2(10,20)
print(c1.add(100,200))

300


# some inheritance
# parent class


In [9]:
class person(object):
    #constructor
    def __init__(self,name):
        self.name = name
    def getname(self):
        return self.name
    def isEmployee(self):
        return False
     # derived class
class Employee(person):
    def isEmployee(self):
        return True

emp=person("anil")
print(emp.getName(),isEmployee())
 
emp1 = Employee("Akhil")
print(emp.getName(),isEmployee())

AttributeError: 'person' object has no attribute 'getName'

# reshape the given array

# numpy.reshape(arrayName,reshape,order="c")

In [9]:
import numpy as np

In [16]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)


[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
A = np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[1][3] = 14
np.asarray(A)[3][3] = 16
print(A)

[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1 16]]


In [4]:
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

# indexing and slicing of Numpy

In [13]:
a1 = np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [15]:
a1 = np.array([(1,2,3),(4,5,6)])
print("First Row : ",a1[0])


First Row :  [1 2 3]


In [17]:
a1=np.array([(1,2,3),(4,5,6)])
print("second row :",a1[0])

second row : [1 2 3]


In [18]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing row :",a1[:1])

slicing row : [[1 2 3]]


In [23]:
#some math operation on given random numbers
#min -- returns the least number
#max -- returns the large number
#mean -- mean
#median -- median
a1 = np.random.normal(5,1,10)
print(a1)
print("min value = ",np.min(a1))
print("max value = ",np.max(a1))
print("mean value = ",np.mean(a1)) 
print("median value = ",np.median(a1))

[4.54057934 5.55300008 2.63647087 5.93182825 6.20062615 5.59331618
 3.33162673 3.93567111 4.21795438 4.59722395]
min value =  2.636470872316668
max value =  6.200626154610544
mean value =  4.653829703575008
median value =  4.568901645289662


In [33]:
# multiply of 1D arrays
# numpy.dot(x,y) --

c1 = np.array([1,2])
c2 = np.array([4,5])
np.dot(c1,c2)

14

In [31]:
c1 = np.array([(1,2),(3,4)])
c2 = np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

In [41]:
import pandas as pd
dict = {"name":["anil","akhil","dinesh","harsha"],
       "EmailID":["anil@gmail.com","akhil@gmail.com","dinesh@gmail.com","harsha@gmail.com"], 
        "mobilenumber":[9999,8888,7777,6666],
        "address":["hyd","hyd","hyd","hyd"] }
b = pd.DataFrame(dict)
print(b)    
       

     name           EmailID  mobilenumber address
0    anil    anil@gmail.com          9999     hyd
1   akhil   akhil@gmail.com          8888     hyd
2  dinesh  dinesh@gmail.com          7777     hyd
3  harsha  harsha@gmail.com          6666     hyd


In [1]:
#supermarket.csv - analysis (which product having higher % of selling)
#which products having least selling %

import pandas as pd
products =pd.read_csv("Filename.csv")
print(products)

FileNotFoundError: [Errno 2] File b'Filename.csv' does not exist: b'Filename.csv'